CREATE TABLE bach_token (id INT AUTO_INCREMENT NOT NULL, filename VARCHAR(255) NOT NULL, bach_token VARCHAR(32) NOT NULL, action TINYINT(1) NOT NULL, PRIMARY KEY(id))
CREATE TABLE daos_prepared (id INT AUTO_INCREMENT NOT NULL, href VARCHAR(1000) NOT NULL, end_dao VARCHAR(1000) NOT NULL, action TINYINT(1) NOT NULL, last_file VARCHAR(1000) DEFAULT NULL, PRIMARY KEY(id))
UPDATE comments SET eadfile_id = :uniqid  WHERE id = :id
UPDATE comments SET docid = :docid  WHERE id = :id
CREATE TABLE daos_prepared (id INT AUTO_INCREMENT NOT NULL, href VARCHAR(1000) NOT NULL, end_dao VARCHAR(1000) NOT NULL, action TINYINT(1) NOT NULL, last_file VARCHAR(1000), PRIMARY KEY(id))
