SELECT * FROM (SELECT 1 AS id UNION ALL SELECT 2) AS t;
CREATE TABLE example (' 'id int UNIQUE DEFERRABLE INITIALLY DEFERRED)
CREATE TABLE %s (taste VARCHAR(20))
CREATE INDEX tmp_index ON cachalot_test(name);
SELECT * FROM %s;
INSERT INTO example VALUES (1)
