CREATE TABLE users ( id NUMBER(38,0) PRIMARY KEY NOT NULL, name VARCHAR(200) default 'Billy', fired_at timestamp )
SELECT cost2 FROM widgets WHERE id = ?
CREATE TABLE `stuff` ( `id` bigint NOT NULL auto_increment, `value` varchar(50) NULL, PRIMARY KEY (`id`) )
CREATE TABLE users ( id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1), name VARCHAR(200) default 'Billy' NULL, fired_at TIMESTAMP )
SELECT weight, cost1 FROM widgets WHERE ad_description = ?
SELECT id FROM widgets WHERE id = ?").execute_reader(::StringWithExtraPowers.new("2
UPDATE widgets SET super_number = ?  WHERE id = 10
SELECT whitepaper_text FROM widgets WHERE id = ?
CREATE TABLE users ( id BIGINT PRIMARY KEY DEFAULT -1, name VARCHAR(200) default 'Billy', fired_at TIMESTAMP )
SELECT id FROM widgets WHERE release_datetime = ? ORDER BY id
SELECT release_date FROM widgets WHERE ad_description = ?
SELECT weight FROM widgets WHERE ad_description = ?
SELECT * FROM non_existent_widgets WHERE ad_description = ? AND white_paper_text = ?
SELECT * FROM widgets WHERE id between ?
SELECT name FROM users WHERE id = 900
SELECT cost1 FROM widgets WHERE id = ?
SELECT cad_drawing FROM widgets WHERE id = ?
SELECT cost2 FROM widgets WHERE ad_description = ?
SELECT cad_drawing FROM widgets WHERE ad_description = ?
SELECT cost1 FROM widgets WHERE ad_description = ?
SELECT release_datetime FROM widgets WHERE ad_description = ?
SELECT release_date FROM widgets WHERE id = ?
select 1 from INFORMATION_SCHEMA.SYSTEM_USERS
SELECT id FROM widgets WHERE id = ?").execute_reader(BigDecimal("2.0
CREATE TABLE `invoices` ( `invoice_number` varchar(50) NOT NULL, PRIMARY KEY (`invoice_number`) )
SELECT release_timestamp FROM widgets WHERE id = ?
SELECT id FROM widgets WHERE id = ?
SELECT 1 FROM dual
SELECT whitepaper_text FROM widgets WHERE whitepaper_text = ?
SELECT sessiontimezone FROM dual
SELECT ad_description FROM widgets WHERE id = ?
SELECT * FROM zoos WHERE name = `Dallas` AND acreage > 40
update widgets set flags = true  where id = 2
SELECT code FROM widgets WHERE ad_description = ? order by id
SELECT * FROM zoos WHERE name = ?", "Dallas
CREATE TABLE `users` ( `id` int(11) NOT NULL auto_increment, `name` varchar(200) default 'Billy' NULL, `fired_at` timestamp, PRIMARY KEY (`id`) )
SELECT * FROM zoos
SELECT name FROM users WHERE name = #{@n}\'#{name}\'
UPDATE users SET name = ?  WHERE id = 900
SELECT super_number FROM widgets WHERE id = ?
select * from master..syslanguages
SELECT release_datetime FROM widgets WHERE id = ?
SELECT id FROM widgets WHERE flags = ?
SELECT flags FROM widgets WHERE ad_description = ?
SELECT number_sold FROM widgets WHERE ad_description = ?
SELECT release_date FROM widgets WHERE release_date = '0001-01-01'
CREATE TABLE `users_mb4` ( `id` int(11) NOT NULL auto_increment, `name` varchar(200), PRIMARY KEY (`id`) )
SELECT name FROM users_mb4
SELECT code FROM widgets WHERE ad_description = ?
update widgets set release_timestamp = ?  where id = 1
SELECT id FROM widgets WHERE release_date = ? ORDER BY id
CREATE TABLE users ( id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY, name VARCHAR(200) default 'Billy', fired_at TIMESTAMP )
SELECT SIGN(1) FROM SYSPROGRESS.SYSCALCTABLE
SELECT id FROM widgets WHERE ad_description = ?
SELECT * FROM zoos WHERE name = `Dallas`
CREATE TABLE `widgets` ( `id` int(11) NOT NULL auto_increment, `code` char(8) default 'A14' NULL, `name` varchar(200) default 'Super Widget' NULL, `shelf_location` tinytext NULL, `description` text NULL, `image_data` blob NULL, `ad_description` mediumtext NULL, `ad_image` mediumblob NULL, `whitepaper_text` longtext NULL, `cad_drawing` longblob NULL, `flags` boolean default false, `number_in_stock` smallint default 500, `number_sold` mediumint default 0, `super_number` bigint default 9223372036854775807, `weight` float default 1.23, `cost1` double default 10.23, `cost2` decimal(8,2) default 50.23, `release_date` date default '2008-02-14', `release_datetime` datetime default '2008-02-14 00:31:12', `release_timestamp` timestamp NULL default '2008-02-14 00:31:31', `status` enum('active','out of stock') NOT NULL default 'active', PRIMARY KEY (`id`) )
SELECT release_datetime FROM widgets WHERE id = ? OR id = ? ORDER BY id
SELECT ad_description FROM widgets WHERE cad_drawing = ?").execute_reader(::Extlib::ByteArray.new("CAD \001 \000 DRAWING
CREATE TABLE users ( id INTEGER IDENTITY, name VARCHAR(200) default 'Billy' NULL, fired_at TIMESTAMP )
CREATE TABLE widgets ( id BIGINT PRIMARY KEY DEFAULT -1, code CHAR(8) DEFAULT 'A14', name VARCHAR(200) DEFAULT 'Super Widget', shelf_location VARCHAR(4000), description VARCHAR(4000), image_data BLOB, ad_description VARCHAR(4000), ad_image BLOB, whitepaper_text CLOB, class_name VARCHAR(4000), cad_drawing BLOB, flags BIT DEFAULT 0, number_in_stock SMALLINT DEFAULT 500, number_sold INTEGER DEFAULT 0, super_number BIGINT DEFAULT 9223372036854775807, weight FLOAT DEFAULT 1.23, cost1 REAL DEFAULT 10.23, cost2 DECIMAL DEFAULT 50.23, release_date DATE DEFAULT '2008-02-14', release_datetime TIMESTAMP DEFAULT '2008-02-14 00:31:12', release_timestamp TIMESTAMP DEFAULT '2008-02-14 00:31:31' )
SELECT release_datetime FROM widgets WHERE release_datetime = '0000-00-00 00:00:00'
SELECT id FROM widgets WHERE id = ?").execute_reader("2
SELECT whitepaper_text FROM widgets WHERE ad_description = ?
SELECT release_timestamp FROM widgets WHERE id < ? order by id
CREATE TABLE invoices ( id NUMBER(38,0) PRIMARY KEY NOT NULL, invoice_number VARCHAR2(50) NOT NULL )
SELECT ad_image FROM widgets WHERE ad_description = ?
SELECT * FROM widgets WHERE id in ?
SELECT 1 FROM SYSIBM.SYSDUMMY1
SELECT * FROM zoos WHERE name = ? AND acreage > ?", "Dallas
SELECT name, whitepaper_text FROM widgets WHERE ad_description = ?
SELECT code, name FROM widgets WHERE ad_description = ? AND whitepaper_text = ?
SELECT class_name FROM widgets WHERE ad_description = ?
SELECT class_name FROM widgets WHERE class_name = ?
SELECT code, name FROM widgets WHERE ad_description = ?
SELECT code, name FROM widgets WHERE ad_description = ? order by id
SELECT id FROM widgets WHERE ad_description IN (?) ORDER BY id
CREATE TABLE invoices ( id BIGINT PRIMARY KEY DEFAULT -1, invoice_number VARCHAR(50) NOT NULL )
SELECT flags FROM widgets WHERE id = ?
SELECT ad_description FROM widgets WHERE ad_description = ?
SELECT id FROM widgets WHERE id = ?").execute_reader(::Extlib::ByteArray.new("2
SELECT release_date FROM widgets WHERE release_date = '0000-00-00'
