SELECT COUNT(*) FROM \"" + tablename +'
CREATE TABLE MINIMAL_ENTITY (_id INTEGER PRIMARY KEY)
SELECT count(*) from MINIMAL_ENTITY
INSERT INTO MINIMAL_ENTITY VALUES (4)
INSERT INTO MINIMAL_ENTITY VALUES (1)
INSERT INTO MINIMAL_ENTITY VALUES (5)
INSERT INTO MINIMAL_ENTITY VALUES (3)
SELECT COUNT(*) FROM ");
