SELECT COUNT(*) FROM {$wpdb->prefix}redirection_groups WHERE module_id=3
SELECT * FROM {$wpdb->prefix}redirection_items $where ORDER BY $orderby $direction 
SELECT COUNT(*) FROM {$wpdb->prefix}redirection_404
SELECT COUNT(*) FROM {$wpdb->prefix}redirection_groups 
CREATE TABLE `{$prefix}redirection_items` (	`id` int(11) unsigned NOT NULL AUTO_INCREMENT,	`url` mediumtext NOT NULL,	`regex` int(11) unsigned NOT NULL DEFAULT '0',	`position` int(11) unsigned NOT NULL DEFAULT '0',	`last_count` int(10) unsigned NOT NULL DEFAULT '0',	`last_access` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',	`group_id` int(11) NOT NULL DEFAULT '0',	`status` enum('enabled','disabled') NOT NULL DEFAULT 'enabled',	`action_type` varchar(20) NOT NULL,	`action_code` int(11) unsigned NOT NULL,	`action_data` mediumtext,	`match_type` varchar(20) NOT NULL,	`title` text,	PRIMARY KEY (`id`),	KEY `url` (`url`(191)),	KEY `status` (`status`),	KEY `regex` (`regex`),	KEY `group_idpos` (`group_id`,`position`),	KEY `group` (`group_id`))
CREATE TABLE `{$prefix}redirection_logs` ( `id` int(11) unsigned NOT NULL AUTO_INCREMENT, `created` datetime NOT NULL, `url` mediumtext NOT NULL, `sent_to` mediumtext, `agent` mediumtext NOT NULL, `referrer` mediumtext, `redirection_id` int(11) unsigned DEFAULT NULL, `ip` varchar(45) DEFAULT NULL, `module_id` int(11) unsigned NOT NULL, `group_id` int(11) unsigned DEFAULT NULL, PRIMARY KEY (`id`), KEY `created` (`created`), KEY `redirection_id` (`redirection_id`), KEY `ip` (`ip`), KEY `group_id` (`group_id`), KEY `module_id` (`module_id`))
SELECT * FROM {$wpdb->prefix}WP_SEO_Redirection
CREATE TABLE IF NOT EXISTS `{$prefix}redirection_logs` (		 `id` int(11) unsigned NOT NULL AUTO_INCREMENT,		 `created` datetime NOT NULL,		 `url` mediumtext NOT NULL,		 `sent_to` mediumtext,		 `agent` mediumtext NOT NULL,		 `referrer` mediumtext,		 `redirection_id` int(11) unsigned DEFAULT NULL, 		 `ip` varchar(45) DEFAULT NULL,		 `module_id` int(11) unsigned NOT NULL,		 `group_id` int(11) unsigned DEFAULT NULL,		 PRIMARY KEY (`id`),		 KEY `created` (`created`),		 KEY `redirection_id` (`redirection_id`),		 KEY `ip` (`ip`),		 KEY `group_id` (`group_id`),		 KEY `module_id` (`module_id`)	 	)
SELECT * FROM {$wpdb->prefix}redirection_groups $where " . $wpdb->prepare( "ORDER BY $orderby $direction LIMIT %d,%d
SELECT COUNT(*) FROM {$wpdb->prefix}postmeta INNER JOIN {$wpdb->prefix}posts ON {$wpdb->prefix}posts.ID={$wpdb->prefix}postmeta.post_id WHERE {$wpdb->prefix}postmeta.meta_key = '_wp_old_slug' AND {$wpdb->prefix}posts.post_status='publish' AND {$wpdb->prefix}posts.post_type IN ('page', 'post')
CREATE TABLE `{$prefix}redirection_items` (	`id` int(11) unsigned NOT NULL AUTO_INCREMENT,	`url` mediumtext NOT NULL,	`regex` int(11) unsigned NOT NULL DEFAULT '0',	`position` int(11) unsigned NOT NULL DEFAULT '0',	`last_count` int(10) unsigned NOT NULL DEFAULT '0',	`last_access` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',	`group_id` int(11) NOT NULL DEFAULT '0',	`status` enum('enabled','disabled') NOT NULL DEFAULT 'enabled',	`action_type` varchar(20) NOT NULL,	`action_code` int(11) unsigned NOT NULL,	`action_data` mediumtext,	`match_type` varchar(20) NOT NULL,	`title` varchar(50) DEFAULT NULL,	PRIMARY KEY (`id`))
CREATE TABLE `{$prefix}redirection_logs` ( `id` int(11) unsigned NOT NULL AUTO_INCREMENT, `created` datetime NOT NULL, `url` mediumtext NOT NULL, `sent_to` mediumtext, `agent` mediumtext NOT NULL, `referrer` mediumtext, `redirection_id` int(11) unsigned DEFAULT NULL, `ip` varchar(17) NOT NULL DEFAULT '', `module_id` int(11) unsigned NOT NULL, `group_id` int(11) unsigned DEFAULT NULL, PRIMARY KEY (`id`))
SELECT COUNT(*) FROM {$wpdb->prefix}WP_SEO_Redirection
SELECT * FROM {$wpdb->prefix}redirection_404
SELECT * FROM {$wpdb->prefix}redirection_groups LIMIT 1
SELECT COUNT(*) FROM {$wpdb->prefix}redirection_items
CREATE TABLE `{$prefix}redirection_items` (	`id` int(11) unsigned NOT NULL AUTO_INCREMENT,	`url` mediumtext NOT NULL,	`regex` int(11) unsigned NOT NULL DEFAULT '0',	`position` int(11) unsigned NOT NULL DEFAULT '0',	`last_count` int(10) unsigned NOT NULL DEFAULT '0',	`last_access` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',	`group_id` int(11) NOT NULL DEFAULT '0',	`status` enum('enabled','disabled') NOT NULL DEFAULT 'enabled',	`action_type` varchar(20) NOT NULL,	`action_code` int(11) unsigned NOT NULL,	`action_data` mediumtext,	`match_type` varchar(20) NOT NULL,	`title` varchar(50) DEFAULT NULL,	PRIMARY KEY (`id`),	KEY `url` (`url`(191)),	KEY `status` (`status`),	KEY `regex` (`regex`))
CREATE TABLE IF NOT EXISTS `{$prefix}redirection_items` (			`id` int(11) unsigned NOT NULL AUTO_INCREMENT,			`url` mediumtext NOT NULL,			`regex` int(11) unsigned NOT NULL DEFAULT '0',			`position` int(11) unsigned NOT NULL DEFAULT '0',			`last_count` int(10) unsigned NOT NULL DEFAULT '0',			`last_access` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',			`group_id` int(11) NOT NULL DEFAULT '0',			`status` enum('enabled','disabled') NOT NULL DEFAULT 'enabled',			`action_type` varchar(20) NOT NULL,			`action_code` int(11) unsigned NOT NULL,			`action_data` mediumtext,			`match_type` varchar(20) NOT NULL,			`title` text,			PRIMARY KEY (`id`),			KEY `url` (`url`(191)),			KEY `status` (`status`),			KEY `regex` (`regex`),			KEY `group_idpos` (`group_id`,`position`),			KEY `group` (`group_id`)	 )
SELECT * FROM {$wpdb->prefix}$table {$query['where']}
CREATE TABLE `{$prefix}redirection_items` (	`id` int(11) unsigned NOT NULL AUTO_INCREMENT,	`url` mediumtext NOT NULL,	`regex` int(11) unsigned NOT NULL DEFAULT '0',	`position` int(11) unsigned NOT NULL DEFAULT '0',	`last_count` int(10) unsigned NOT NULL DEFAULT '0',	`last_access` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',	`group_id` int(11) NOT NULL DEFAULT '0',	`status` enum('enabled','disabled') NOT NULL DEFAULT 'enabled',	`action_type` varchar(20) NOT NULL,	`action_code` int(11) unsigned NOT NULL,	`action_data` mediumtext,	`match_type` varchar(20) NOT NULL,	PRIMARY KEY (`id`))
SELECT * FROM {$wpdb->prefix}redirection_items
CREATE TABLE `{$prefix}redirection_404` ( `id` int(11) unsigned NOT NULL AUTO_INCREMENT, `created` datetime NOT NULL, `url` varchar(255) NOT NULL DEFAULT '', `agent` varchar(255) DEFAULT NULL, `referrer` varchar(255) DEFAULT NULL, `ip` varchar(45) DEFAULT NULL, PRIMARY KEY (`id`), KEY `created` (`created`), KEY `url` (`url`(191)), KEY `referrer` (`referrer`(191)), KEY `ip` (`ip`))
SELECT COUNT(*) FROM {$wpdb->prefix}{$table} WHERE created < DATE_SUB(NOW(), INTERVAL %d DAY)
CREATE TABLE `{$prefix}redirection_404` ( `id` int(11) unsigned NOT NULL AUTO_INCREMENT, `created` datetime NOT NULL, `url` varchar(255) NOT NULL DEFAULT '', `agent` varchar(255) DEFAULT NULL, `referrer` varchar(255) DEFAULT NULL, `ip` int(10) unsigned NOT NULL, PRIMARY KEY (`id`), KEY `created` (`created`), KEY `url` (`url`(191)), KEY `ip` (`ip`), KEY `referrer` (`referrer`(191)))
CREATE TABLE IF NOT EXISTS `{$prefix}redirection_groups` (			`id` int(11) unsigned NOT NULL AUTO_INCREMENT,			`name` varchar(50) NOT NULL,			`tracking` int(11) NOT NULL DEFAULT '1',			`module_id` int(11) unsigned NOT NULL DEFAULT '0',			`status` enum('enabled','disabled') NOT NULL DEFAULT 'enabled',			`position` int(11) unsigned NOT NULL DEFAULT '0',			PRIMARY KEY (`id`),			KEY `module_id` (`module_id`),			KEY `status` (`status`)		)
SELECT * FROM {$wpdb->prefix}redirection_404 LIMIT %d,%d
CREATE TABLE `{$prefix}redirection_items` (	`id` int(11) unsigned NOT NULL AUTO_INCREMENT,	`url` mediumtext NOT NULL,	`regex` int(11) unsigned NOT NULL DEFAULT '0',	`position` int(11) unsigned NOT NULL DEFAULT '0',	`last_count` int(10) unsigned NOT NULL DEFAULT '0',	`last_access` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',	`group_id` int(11) NOT NULL DEFAULT '0',	`status` enum('enabled','disabled') NOT NULL DEFAULT 'enabled',	`action_type` varchar(20) NOT NULL,	`action_code` int(11) unsigned NOT NULL,	`action_data` mediumtext,	`match_type` varchar(20) NOT NULL,	`title` varchar(50) DEFAULT NULL,	PRIMARY KEY (`id`),	KEY `url` (`url`(191)),	KEY `status` (`status`),	KEY `regex` (`regex`),	KEY `group_idpos` (`group_id`,`position`),	KEY `group` (`group_id`))
SELECT COUNT(*) FROM {$wpdb->prefix}postmeta INNER JOIN {$wpdb->prefix}posts ON {$wpdb->prefix}posts.ID={$wpdb->prefix}postmeta.post_id WHERE {$wpdb->prefix}postmeta.meta_key = '_redirect_rule_from' AND {$wpdb->prefix}posts.post_status='publish'
SELECT * FROM {$wpdb->prefix}redirection_groups ORDER BY id DESC LIMIT 1
SELECT * FROM {$wpdb->prefix}redirection_logs WHERE id=%d
SELECT COUNT(*) FROM {$wpdb->prefix}$table 
SELECT COUNT(*) FROM {$wpdb->prefix}redirection_items 
SELECT * FROM {$wpdb->prefix}redirection_logs LIMIT %d,%d
SELECT COUNT(*) FROM {$wpdb->prefix}redirection_items WHERE group_id=%d
SELECT COUNT(*) FROM {$wpdb->prefix}redirection_groups
SELECT COUNT(*) FROM {$wpdb->prefix}redirection_items INNER JOIN {$wpdb->prefix}redirection_groups ON {$wpdb->prefix}redirection_items.group_id={$wpdb->prefix}redirection_groups.id WHERE {$wpdb->prefix}redirection_groups.module_id=%d
CREATE TABLE `{$prefix}redirection_groups` (	`id` int(11) unsigned NOT NULL AUTO_INCREMENT,	`name` varchar(50) NOT NULL,	`tracking` int(11) NOT NULL DEFAULT '1',	`module_id` int(11) unsigned NOT NULL DEFAULT '0',	`status` enum('enabled','disabled') NOT NULL DEFAULT 'enabled',	`position` int(11) unsigned NOT NULL DEFAULT '0',	PRIMARY KEY (`id`))
SELECT ID FROM {$wpdb->posts} ORDER BY RAND() LIMIT 0,1
SELECT * FROM {$wpdb->prefix}redirection_404 WHERE id=%d
SELECT * FROM {$wpdb->prefix}redirection_groups
CREATE TABLE `{$prefix}redirection_modules` ( `id` int(11) unsigned NOT NULL auto_increment, `type` varchar(20) NOT NULL default '', `name` varchar(50) NOT NULL default '', `options` mediumtext, PRIMARY KEY ( `id`), KEY `name` (`name`), KEY `type` (`type`))
SELECT * FROM {$wpdb->prefix}redirection_items WHERE id=%d
SELECT COUNT(*) FROM {$wpdb->prefix}redirection_logs
CREATE TABLE `{$prefix}redirection_logs` ( `id` int(11) unsigned NOT NULL AUTO_INCREMENT, `created` datetime NOT NULL, `url` mediumtext NOT NULL, `sent_to` mediumtext, `agent` mediumtext NOT NULL, `referrer` mediumtext, `redirection_id` int(11) unsigned DEFAULT NULL, `ip` varchar(17) NOT NULL DEFAULT '', `module_id` int(11) unsigned NOT NULL, `group_id` int(11) unsigned DEFAULT NULL, PRIMARY KEY (`id`), KEY `created` (`created`), KEY `redirection_id` (`redirection_id`), KEY `ip` (`ip`), KEY `group_id` (`group_id`), KEY `module_id` (`module_id`))
CREATE TABLE IF NOT EXISTS `{$prefix}redirection_404` (		 `id` int(11) unsigned NOT NULL AUTO_INCREMENT,		 `created` datetime NOT NULL,		 `url` varchar(255) NOT NULL DEFAULT '',		 `agent` varchar(255) DEFAULT NULL,		 `referrer` varchar(255) DEFAULT NULL,		 `ip` varchar(45) DEFAULT NULL,		 PRIMARY KEY (`id`),		 KEY `created` (`created`),		 KEY `url` (`url`(191)),		 KEY `referrer` (`referrer`(191)),		 KEY `ip` (`ip`)	 	)
SELECT * FROM {$wpdb->prefix}redirection_items ORDER BY id DESC LIMIT 1
SELECT * FROM {$wpdb->prefix}redirection_groups WHERE module_id=%d
SELECT ID FROM {$wpdb->prefix}posts WHERE post_status='publish' AND post_password='' AND post_type='post' ORDER BY RAND() LIMIT 0,1
CREATE TABLE `{$prefix}redirection_groups` (	`id` int(11) unsigned NOT NULL AUTO_INCREMENT,	`name` varchar(50) NOT NULL,	`tracking` int(11) NOT NULL DEFAULT '1',	`module_id` int(11) unsigned NOT NULL DEFAULT '0',	`status` enum('enabled','disabled') NOT NULL DEFAULT 'enabled',	`position` int(11) unsigned NOT NULL DEFAULT '0',	PRIMARY KEY (`id`),	KEY `module_id` (`module_id`),	KEY `status` (`status`))
