CREATE TABLE IF NOT EXISTS `${TABLE_NAME}` (`TITLE` TEXT, `TEXT` TEXT, `TICKER` TEXT, `ID` INTEGER PRIMARY KEY AUTOINCREMENT, `DATETIME` TEXT, `DATE` TEXT)
CREATE TABLE IF NOT EXISTS `${TABLE_NAME}` (`DEVICE` TEXT, `CHANGES` TEXT, `ID` INTEGER PRIMARY KEY AUTOINCREMENT, `DATETIME` TEXT, `DATE` TEXT, `SAVE_DATETIME` TEXT)
SELECT * FROM ${FcmHistoryChangeEntity.tableName} WHERE ${FcmHistoryEntity.columnDatetime} <= :date
SELECT * FROM ${FcmHistoryChangeEntity.tableName} WHERE ${FcmHistoryEntity.columnDate} = :date ORDER BY ${FcmHistoryEntity.columnDatetime} DESC
SELECT * FROM ${FcmHistoryMessageEntity.tableName} WHERE ${FcmHistoryEntity.columnDatetime} <= :date
SELECT * FROM ${FcmHistoryMessageEntity.tableName} WHERE ${FcmHistoryEntity.columnDate} = :date ORDER BY ${FcmHistoryEntity.columnDatetime} DESC
CREATE TABLE IF NOT EXISTS `${TABLE_NAME}` (`DEVICE` TEXT, `CHANGES` TEXT, `ID` INTEGER PRIMARY KEY AUTOINCREMENT, `DATETIME` TEXT, `DATE` TEXT)
CREATE TABLE IF NOT EXISTS `${TABLE_NAME}` (`TITLE` TEXT, `TEXT` TEXT, `TICKER` TEXT, `ID` INTEGER PRIMARY KEY AUTOINCREMENT, `DATETIME` TEXT, `DATE` TEXT, `SAVE_DATETIME` TEXT)
CREATE TABLE IF NOT EXISTS room_master_table (id INTEGER PRIMARY KEY,identity_hash TEXT)
