SELECT * FROM RUN_EXTRA");
SELECT ID, FILENAME, NATIVE_ID FROM RUN
SELECT MAX(ID) FROM CHROMATOGRAM
CREATE INDEX run_extra ON RUN_EXTRA(RUN_ID);
CREATE INDEX spec_rt_idx ON SPECTRUM(RETENTION_TIME);
SELECT CHROMATOGRAM_ID, COMPRESSION, DATA_TYPE, DATA FROM DATA WHERE CHROMATOGRAM_ID = %s
SELECT * FROM %s.%s_tmp_delete
CREATE INDEX spec_mslevel ON SPECTRUM(MSLEVEL);
SELECT MAX(ID) FROM RUN
CREATE TABLE CHROMATOGRAM(ID INT PRIMARY KEY NOT NULL,RUN_ID INT,NATIVE_ID TEXT NOT NULL)
SELECT MAX(ID) FROM SPECTRUM
CREATE INDEX product_chr_idx ON DATA(CHROMATOGRAM_ID);
CREATE INDEX spec_rt_idx ON SPECTRUM(RETENTION_TIME)H#gindexdata_sp_idxDATA
SELECT * FROM RUN");
SELECT ID FROM CHROMATOGRAM WHERE NATIVE_ID LIKE '%s%%'
CREATE INDEX data_sp_idx ON DATA(SPECTRUM_ID);
CREATE INDEX product_sp_idx ON DATA(SPECTRUM_ID);
SELECT COUNT(*) FROM SPECTRUM
CREATE INDEX spec_run ON SPECTRUM(RUN_ID);
CREATE INDEX precursor_sp_idx ON DATA(SPECTRUM_ID)X/{indexprecursor_chr_idxDATA
SELECT CHROMATOGRAM_ID, COMPRESSION, DATA_TYPE, DATA FROM DATA WHERE CHROMATOGRAM_ID IN (
SELECT * FROM SPECTRUM");
CREATE INDEX chrom_run ON CHROMATOGRAM(RUN_ID);
SELECT ID FROM CHROMATOGRAM WHERE NATIVE_ID IN %s
CREATE INDEX data_chr_idx ON DATA(CHROMATOGRAM_ID);
SELECT * FROM %s_TMP;
SELECT MAX(ID) FROM RUN) +1, FILENAME, NATIVE_ID FROM other.RUN;
CREATE INDEX precursor_sp_idx ON DATA(SPECTRUM_ID);
CREATE INDEX precursor_chr_idx ON DATA(CHROMATOGRAM_ID);
SELECT COUNT(*) FROM CHROMATOGRAM
SELECT CHROMATOGRAM_ID, COMPRESSION, DATA_TYPE, DATA FROM DATA INNER JOIN CHROMATOGRAM ON CHROMATOGRAM.ID = CHROMATOGRAM_ID WHERE NATIVE_ID = %s
