CREATE TABLE planet ( id int IDENTITY, name varchar(32) DEFAULT NULL, code varchar(64) GENERATED ALWAYS AS (name || '-' || id))
INSERT INTO AUTHOR VALUES(1,'James Brown')
CREATE TABLE mbtest.order_header( order_id integer NOT NULL, cust_name character varying(50) NOT NULL, CONSTRAINT order_header_pkey PRIMARY KEY (order_id))
insert into users values(1, 'Pocoyo')
CREATE TABLE mbtest.test_sqlxml ( id serial PRIMARY KEY, content XML)
insert into users values(4, 'User4', 1, 1)
create table a ( id int, name varchar(20))
select name from car where doors = #{doors2[1]}
create table groups ( id int, state varchar(20))
SELECT * FROM post ORDER BY id
insert into permissions values ('resource1', 'user1', 'read')
INSERT INTO account VALUES('ACID','acid@yourdomain.com','ABC', 'XYX', 'OK', '901 San Antonio Road', 'MS UCUP02-206', 'Palo Alto', 'CA', '94303', 'USA', '555-555-5555')
SELECT * FROM extensive_subject
UPDATE person SET firstName = Simone  WHERE id = 1
create table Father ( id int, name varchar(100), grand_father_id int)
create table signon (username varchar(25) not null,password varchar(25) not null,constraint pk_signon primary key (username))
create table supplier (suppid int not null,name varchar(80) null,status varchar(2) not null,addr1 varchar(80) null,addr2 varchar(80) null,city varchar(80) null,state varchar(80) null,zip varchar(5) null,phone varchar(80) null,constraint pk_supplier primary key (suppid))
insert into users values(4, 'User4', 2, 1)
create table part ( part_id int, name varchar(20), car_id int)
insert into users values(3, 'User3', 3, 1)
CREATE TABLE table_foo ( id INTEGER PRIMARY KEY, id_bar INTEGER NOT NULL)
SELECT * FROM PRODUCT WHERE PRODUCTID = ?", "FI-SW-01
select * from sptest.names where id >= lowestId and id <= highestId;
update product set category = ?  where productid = ?
CREATE TABLE country ( Id int IDENTITY, countryname varchar(255) DEFAULT NULL, countrycode varchar(255) DEFAULT NULL,)
select * from users order by id
create table user_account ( id int, name varchar(20))
create table person (id int, nr_department int)
create table parent_child(	idparent integer, 	idchild_from integer, 	idchild_to integer)
INSERT INTO POST VALUES(3,'content 3',1)
select * from sptest.items where name_id in (select id from sptest.names where id = nameId);
insert into users values(3, 'User3')
insert into permissions values ('resource2', 'user1', 'delete')
create table breeder ( id int, name varchar(20))
insert into users values(2, 'User2', 1, 3)
insert into users values(4, 'User4', 1, 2)
SELECT * FROM BLOG WHERE CATEGORY = 'NONE'
INSERT INTO test VALUES('A1', 'B1')
create table signon (username varchar(25) not null,password varchar(25) not null,constraint pk_signon primary key (username))
create table users2 (id int IDENTITY,name varchar(16))
select * from sptest.names;
create table user (id int,username varchar(32) not null,password varchar(128) not null,administrator boolean,primary key (id))
create table users ( id int, name varchar(20), funkyNumber decimal(38), roundingMode int)
select * from ${table} where id = #{id}
select * from mbtest.order_detail order by order_id, line_number ;
insert into users values(3, 'User3', 2, 1)
create table folder (id int, name varchar(100), parent_id int)
create table table2 (id int generated by default as identity (start with 22) not null,name varchar(20),name_fred varchar(25) generated always as (name || '_fred'))
create table names (id int,firstName varchar(20),lastName varchar(20))
select * from FOO;
create table articles ( id int, name varchar(20), author_id int, coauthor_id int)
select * from users where id = 2
SELECT ID, CONTENT FROM TEST_CLOB WHERE ID = #{id}
insert into users values(1, 'User1')
create table person (id int,name varchar(32),billing_address_id int,shipping_address_id int,room_id int)
create table sptest.books ( id integer not null, name varchar(20), genre1 integer, genre2 integer, primary key(id))
CREATE TABLE SimpleChildObject (id VARCHAR(5) NOT NULL, simple_object_id VARCHAR(5) NOT NULL)
create index productCat on product (category);
INSERT INTO profile VALUES('ACID','english','CATS',1,1)
create table person (person_id int, person_name varchar(32))
SELECT * FROM author WHERE username = ?", "someone
select * from company where id = #{id}
create table brand (id int,name varchar(32))
insert into users values(#{id}, #{name})
select id, name from users where id=1
CREATE TABLE extensive_subject ( aByte TINYINT, aShort SMALLINT, aChar CHAR, anInt INT, aLong BIGINT, aFloat FLOAT, aDouble DOUBLE, aBoolean BIT, aString VARCHAR(255), anEnum VARCHAR(50), aClob LONGVARCHAR, aBlob LONGVARBINARY, aTimestamp TIMESTAMP)
SELECT * FROM BLOG WHERE CATEGORY = ?
create table Child ( id int, name varchar(100), father_id int, grand_father_id int)
select id, name_fred from table2 where id = identity()", keyProperty="nameId,generatedName", keyColumn="ID,NAME_FRED
select col1, col2 from parent where id = #{id}
select * from inventory;
create table person ( id int, firstName varchar(100), lastName varchar(100), personType varchar(100) DEFAULT NULL)
select userid from account where userid = 'j2ee';
create index itemProd on item (productid);
select id, firstname, lastname from person
insert into users values (#{id}, #{name})
SELECT * FROM PRODUCT
SELECT * FROM BLOG WHERE \r\n ID = ?
SELECT * FROM BLOG WHERE CATEGORY = 'DEFAULT'
create table table1 ( id int, a varchar(20), col_a varchar(20), col_b varchar(20), col_c varchar(20))
CREATE TABLE order_header ( order_id integer NOT NULL, cust_name varchar(50) NOT NULL, PRIMARY KEY (order_id) )
CREATE TABLE table_bar ( id INTEGER PRIMARY KEY)
create table blog ( id int, title varchar(16), author_id int, co_author_id int)
insert into groups values(2, 'Valentina', 'User1,User2,User3')
insert into users values(2, 'User2', 1, 2)
select * from post where author_id = #{id} order by id
select name from car where doors = #{doors[1]}
create table int_bool ( id identity, key integer, value boolean)
CREATE TABLE test_clob ( id INT PRIMARY KEY, content CLOB)
create table Child ( id int, Name varchar(20), SurName varchar(20), Age int, ParentId varchar(20))
select * from person
insert into folder values(3, 'Folder 2', 1)
create table users ( id int, name varchar(128))
INSERT INTO extensive_subjectVALUES (1, 1, 'a', 1, 1, 1, 1.0, 1, 'a', 'AVALUE', 'ACLOB', 'aaaaaabbbbbb', CURRENT_TIMESTAMP)
select * from users where name = #{map}
insert into Parent values (2, 'Juan', 'Perez')
create table users ( id int, name varchar(20), first_attr_1 varchar(3), first_attr_2 varchar(3), second_attr_1 varchar(3), second_attr_2 varchar(3),)
insert into users values(1, 'User1', 2, 2)
select * from sptest.books order by id;
select * from users
select * from mbtest.order_header where order_id = ORDER_NUMBER;
INSERT INTO sequence VALUES('ordernum', 1000)
select * from A
SELECT * FROM subject
create table users ( id int, name varchar(20), phone varchar(20), phone_number bigint)
create table pet (pet_id int, owner_id int, pet_name varchar(32))
select * from users where id = #{value}
SELECT ID, CONTENT FROM TEST_BLOB WHERE ID = #{id}
create table items ( id int, owner int, name varchar(20))
create table ibtest.numerics ( id int, tinynumber tinyint, smallnumber smallint, longinteger bigint, biginteger bigint, numericnumber numeric(10,2), decimalnumber decimal(10,2), realnumber real, floatnumber float, doublenumber double)
create table room (room_id int,room_name varchar(32))
CREATE TABLE mbtest.test_identity( first_name character varying(30), last_name character varying(30), name_id serial NOT NULL, CONSTRAINT test_identity_pkey PRIMARY KEY (name_id))
create table users ( id int, name varchar(20), owner_id int)
CREATE TABLE author (id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),username VARCHAR(255) NOT NULL,password VARCHAR(255) NOT NULL,email VARCHAR(255) NOT NULL,bio CLOB,favourite_section VARCHAR(25),PRIMARY KEY (id))
SELECT * FROM author ORDER BY id
select * from user_profile
create table Parent ( id int, Name varchar(20), SurName varchar(20))
create table sptest.names ( id integer, first_name varchar(20), last_name varchar(20), primary key(id))
INSERT INTO account VALUES('j2ee','yourname@yourdomain.com','ABC', 'XYX', 'OK', '901 San Antonio Road', 'MS UCUP02-206', 'Palo Alto', 'CA', '94303', 'USA', '555-555-5555')
SELECT * FROM PERSON WHERE ID=?
CREATE TABLE post (id INT,blog_id INT,body VARCHAR(255))
create table groups (id int,owner varchar(16),members varchar(256))
create table product (productid varchar(10) not null,category varchar(10) not null,name varchar(80) null,descn varchar(255) null,constraint pk_product primary key (productid),constraint fk_product_1 foreign key (category)references category (catid))
CREATE TABLE address( id int NOT NULL, CONSTRAINT pk_address PRIMARY KEY (id),)
SELECT * FROM author WHERE id = ?
create table user_profile ( id int, name varchar(20))
insert into users values(2, 'User2', 1, 1)
create table child (id int,parent_id int,name varchar(20))
INSERT INTO signon VALUES('j2ee','j2ee')
create table udata ( user_id int, num int)
create table orders (orderid int not null,userid varchar(80) not null,orderdate date not null,shipaddr1 varchar(80) not null,shipaddr2 varchar(80) null,shipcity varchar(80) not null,shipstate varchar(80) not null,shipzip varchar(20) not null,shipcountry varchar(20) not null,billaddr1 varchar(80) not null,billaddr2 varchar(80) null,billcity varchar(80) not null,billstate varchar(80) not null,billzip varchar(20) not null,billcountry varchar(20) not null,courier varchar(80) not null,totalprice decimal(10,2) not null,billtofirstname varchar(80) not null,billtolastname varchar(80) not null,shiptofirstname varchar(80) not null,shiptolastname varchar(80) not null,creditcard varchar(80) not null,exprdate varchar(7) not null,cardtype varchar(80) not null,locale varchar(80) not null,constraint pk_orders primary key (orderid))
SELECT * FROM ${schema?:prod}.${tableName == null ? 'users' : tableName} ORDER BY ${orderColumn}", props)).isEqualTo("SELECT * FROM prod.${tableName == null ? 'users' : tableName} ORDER BY ${orderColumn}
select userid from account where userid = 'j2ee'
CREATE TABLE t_account_address( account_uuid CHAR(36) PRIMARY KEY ,zip_code CHAR(7) ,address VARCHAR(256))
create table permissions ( resourceName varchar(20), principalName varchar(20), permission varchar(20))
insert into users values(1, 'User1', 1, 1)
create table users (id int,name varchar(16))
CREATE TABLE param_test ( id VARCHAR(255) NOT NULL, size BIGINT, PRIMARY KEY (id))
create table category (catid varchar(10) not null,name varchar(80) null,descn varchar(255) null,constraint pk_category primary key (catid))
select * from users where name = #{name}
select * from author where id = ?
insert into Child values (1, 'Ana', 'Garcia', 1, 1)
CREATE TABLE mbtest.sections ( section_id int PRIMARY KEY, name character varying(30))
create table users ( uid int, name varchar(20))
create table string_string ( id identity, key varchar(255), value varchar(255))
SELECT * FROM subject WHERE id = #{id}
create table hsql (id int,name varchar(20))
create table properties (	item_id int, 	property_id int, 	value varchar(20))
create table pets ( id int, owner int, breeder int, name varchar(20))
create table productattribute (nr_id int)
INSERT INTO subject VALUES (1, 'a', 10, 100, 45, 1, CURRENT_TIMESTAMP)
CREATE TABLE sequence(name varchar(30) not null,nextid int not null,constraint pk_sequence primary key (name))
create table SomeTable ( id int, field1 varchar(20), field2 varchar(20), field3 varchar(20))
SELECT * FROM BLOG WHERE ID = ?
insert into users values(3, 'User3', 1, 1)
select * from sptest.items;
SELECT 1 FROM INFORMATION_SCHEMA.SYSTEM_USERS
create table phone (id int,phone varchar(32),area_code varchar(2))
CREATE TABLE tag (id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,name VARCHAR(255) NOT NULL,PRIMARY KEY (id))
create table users ( id int, name varchar(20), group_id int, rol_id int)
select firstName from ibtest.names where id=${_parameter}
create table ibtest.names (id int,firstName varchar(20),lastName varchar(20))
create table users ( id int, color int)
CREATE TABLE person ( id int, firstName varchar(100), lastName varchar(100))
create table item (itemid varchar(10) not null,productid varchar(10) not null,listprice decimal(10,2) null,unitcost decimal(10,2) null,supplier int null,status varchar(2) null,attr1 varchar(80) null,attr2 varchar(80) null,attr3 varchar(80) null,attr4 varchar(80) null,attr5 varchar(80) null,constraint pk_item primary key (itemid),constraint fk_item_1 foreign key (productid)references product (productid),constraint fk_item_2 foreign key (supplier)references supplier (suppid))
create table users ( id varchar(36), name varchar(20))
insert into users values(2, 'User2')
insert into users values(4, 'User4')
CREATE TABLE order_detail ( order_id integer NOT NULL, line_number integer NOT NULL, quantity integer NOT NULL, item_description varchar(50) NOT NULL, PRIMARY KEY (order_id, line_number) )
create table key_cols ( id identity, col_a integer, col_b integer)
CREATE TABLE SimpleObject (id VARCHAR(5) NOT NULL)
create table depts ( id int, name varchar(20))
create table person (id int,firstName varchar(100),lastName varchar(100),parent int DEFAULT NULL)
create table users2( id int, name varchar(20))
INSERT INTO supplier VALUES (1,'XYZ Pets','AC','600 Avon Way','','Los Angeles','CA','94024','212-947-0797')
create table users ( id int identity, name varchar(20), fld1 int, fld2 int)
insert into users values(1, 'User1', 2, 1)
create table person (id int, name varchar(32))
SELECT * FROM author WHERE id = 99
create table users2 ( id int, name varchar(20), funkyNumber decimal(38), roundingMode varchar(12))
create table authors ( id int, name varchar(20))
create table table1 (id int generated by default as identity (start with 11) not null,name varchar(20))
select id, content from mbtest.test_sqlxml where id = #{id}
select id, username, password, email, bio, favourite_section from author where id = #{id}
insert into common values (#{id}, #{name})
insert into users values(1, 'User1', 2, 3)
CREATE TABLE blog (id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,author_id INT NOT NULL,title VARCHAR(255),PRIMARY KEY (id))
create table users ( id int, name varchar(20), group_id int, state varchar(20))
CREATE TABLE post (id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,blog_id INT,author_id INT NOT NULL,created_on TIMESTAMP NOT NULL,section VARCHAR(25) NOT NULL,subject VARCHAR(255) NOT NULL,body CLOB NOT NULL,draft INT NOT NULL,PRIMARY KEY (id),FOREIGN KEY (blog_id) REFERENCES blog(id))
create table common (id int,name varchar(20))
create table country(	id bigint IDENTITY,	name varchar(20))
create table person ( id int, firstName varchar(100), lastName varchar(100), order_type varchar(100))
create table person(	id int IDENTITY,	name varchar(20))
create table users ( id int, name varchar(20))
select id from product where name = #{value}
create index productName on product (name);
select id, owner, members from groups where id=1
create table student ( id int, name varchar(100), teacher_id int)
create table names ( ID int, FIRST_NAME varchar(20), LAST_NAME varchar(20))
create table bannerdata (favcategory varchar(80) not null,bannername varchar(255) null,constraint pk_bannerdata primary key (favcategory))
create table author ( id int, name varchar(16), reputation int)
insert into users values(1, 'User1', 1, 2)
CREATE TABLE node (id INT NOT NULL,parent_id INT,PRIMARY KEY(id))
CREATE TABLE FOO(field1 integer,field2 integer,field3 integer,field4 integer)
select * from sptest.genres;
create table blobtest.blobs ( id int not null, blob longvarbinary, primary key (id))
create table parent (id int,col1 varchar(20),col2 varchar(20))
SELECT * FROM test AS t LIMIT 1
SELECT firstName, lastName FROM names WHERE lastName LIKE #{name}
create table users ( id int, name varchar(20), state int)
create table pet (id int,parent_id int,name varchar(20))
select * from users where uid = #{id}
create table cars ( carid integer, cartype varchar(20), enginetype varchar(20), enginecylinders integer, brakestype varchar(20))
insert into users values(4, 'User4', 2, 2)
CREATE TABLE post_tag (post_id INT NOT NULL,tag_id INT NOT NULL,PRIMARY KEY (post_id, tag_id))
CREATE TABLE immutables ( id INTEGER PRIMARY KEY, description VARCHAR (30) NOT NULL)
create table users ( id int, name varchar(20), unknownObject varchar(20))
SELECT * FROM blog 
create table nested_bean ( id identity, keya integer, keyb boolean, valuea integer, valueb boolean)
create table person ( id int, firstName varchar(100), lastName varchar(100), jobTitle varchar(100), department varchar(100), personType varchar(100) DEFAULT NULL, employeeType varchar(100) DEFAULT NULL)
create table users ( id int, name varchar(20), logical_delete boolean default false)
select * from users where id = #{id}
SELECT * FROM BLOG WHERE \t ID = ?
CREATE TABLE BLAH(ID INTEGER)
create table names ( id int, firstName varchar(20), lastName varchar(20))
insert into BLAH values (1)
select * from users 
create table inventory (itemid varchar(10) not null,qty int not null,constraint pk_inventory primary key (itemid))
select * from ");
UPDATE author SET username = ?, password = ?, email = ?, bio = ?  WHERE id = ?
create table persons ( id int, name varchar(20))
select * from sptest.names where id = nameId;
insert into hsql values (#{id}, #{name})
insert into users values(2, 'Valentina')
create table car ( name varchar(20), doors int)
CREATE TABLE immutables ( immutable_id INTEGER PRIMARY KEY, immutable_description VARCHAR (30) NOT NULL)
create table parent(	id integer, 	value varchar(20))
SELECT * FROM ITEM
create table users ( id int, name varchar(20), team int)
create table person ( id int, firstName varchar(100), lastName varchar(100), parent_id int default null, parent_firstName varchar(100) default null, parent_lastName varchar(100) default null)
create table product ( id int identity, name varchar(20))
insert into groups values(1, 'Pocoyo', 'User1,User2,User3')
CREATE TABLE comment (id INT,post_id INT,comment VARCHAR(255))
insert into Parent values (1, 'Jose', 'Garcia')
create table groups ( id int, owner int, name varchar(20))
INSERT INTO supplier VALUES (2,'ABC Pets','AC','700 Abalone Way','','San Francisco ','CA','94024','415-947-0797')
SELECT * FROM BLOG WHERE ID = ?
insert into users values (#{id}, #{name})
create table person ( id int, name varchar(32), primary key (id))
insert into Child values (2, 'Rosa', 'Garcia', 4, 1)
CREATE TABLE test_blob ( id INT PRIMARY KEY, content BLOB)
create table teacher ( id int, name varchar(100))
SELECT * FROM blog ORDER BY id
select * from users where id in (
SELECT * FROM ${tableName:users} ORDER BY ${orderColumn:id}", props)).isEqualTo("SELECT * FROM users ORDER BY id
create table ibtest.names (id int,description varchar(20))
select id from users
create table groups ( id int, name varchar(20))
create table zip (state varchar(32),city varchar(32),zip_code int)
create table child(	id integer, 	value varchar(20))
select * from users where id = #{id} and name = #{name}
create table pet (id int,owner_id int,name varchar(32),room_id int)
select * from sptest.names where id in (unnest(ids));
INSERT INTO signon VALUES('ACID','ACID')
insert into users2 values(null, 'Pocoyo')
create table b ( ref int, entry int)
INSERT INTO profile VALUES('j2ee','english','DOGS',1,1)
create table orderstatus (orderid int not null,linenum int not null,timestamp date not null,status varchar(2) not null,constraint pk_orderstatus primary key (orderid, linenum))
SELECT * FROM BLOG
create table users ( id int, name varchar(20), city varchar(20), state char(20))
CREATE TABLE t_account( account_uuid CHAR(36) PRIMARY KEY ,account_name VARCHAR(256) ,birth_date DATETIME)
CREATE TABLE person( id int NOT NULL, id_address integer NOT NULL, CONSTRAINT pk_person PRIMARY KEY (id), CONSTRAINT fk_person_id_address FOREIGN KEY (id_address) REFERENCES address (id) ON UPDATE RESTRICT ON DELETE RESTRICT)
INSERT INTO POST VALUES(1,'content 1',1)
insert into users values(5, 'User5')
insert into permissions values ('resource1', 'user1', 'create')
select name from car where doors = #{doors1[1]}
SELECT * FROM BLOG WHERE NAME = ?
create table Child ( id int, name varchar(100), father_id int)
insert into folder values(2, 'Folder 1', 1)
select * from users order by id;
create table department (nr_id int,nr_attribute int,person int)
SELECT * FROM BLAH
select size from param_test where id = #{id}
create table profile (userid varchar(80) not null,langpref varchar(80) not null,favcategory varchar(30),mylistopt int,banneropt int,constraint pk_profile primary key (userid))
create table car ( car_id int, name varchar(20))
insert into users values (#{id}, #{name})
SELECT id, firstName, lastName, personType FROM person WHERE id = #{id}
select * from users where id = ?
select name_fred from table2 where id = #{nameId}", keyProperty="generatedName", keyColumn="NAME_FRED
create table books ( version int, name varchar(20))
INSERT INTO test VALUES('A2', 'B2')
SELECT firstName, lastName FROM names WHERE lastName LIKE #{name} and 0 < 1
SELECT * FROM blog WHERE id = #{id}
select null from (values(0))
CREATE TABLE mbtest.users ( user_id serial PRIMARY KEY, name character varying(30))
create table table3 (id int not null,name varchar(20))
select * from users where id = #{foo}
select * from users where id = 1
select id, name from users
create table test (	A VARCHAR(32) not null,	B VARCHAR(32) not null)
SELECT * FROM BLOG WHERE ID in ( one = ? AND two = ? AND three = ? )
CREATE TABLE mbtest.order_detail( order_id integer NOT NULL, line_number integer NOT NULL, quantity integer NOT NULL, item_description character varying(50) NOT NULL, CONSTRAINT order_detail_pkey PRIMARY KEY (order_id, line_number))
create table account (userid varchar(80) not null,email varchar(80) not null,firstname varchar(80) not null,lastname varchar(80) not null,status varchar(2) null,addr1 varchar(80) not null,addr2 varchar(40) null,city varchar(80) not null,state varchar(80) not null,zip varchar(20) not null,country varchar(20) not null,phone varchar(80) not null,constraint pk_account primary key (userid))
SELECT * FROM BLOG WHERE ID = ? OR NAME = ?
insert into folder values(5, 'Folder 2_2', 3)
create table person(	id int,	firstname varchar(20),	lastname varchar(20))
create table address (id int,state varchar(32),city varchar(32),phone1_id int,phone2_id int,addr_type int,caution varchar(64))
SELECT * FROM post
INSERT INTO POST VALUES(2,'content 2',1)
select * from author where id in (?,?)
SELECT * FROM BLOG WHERE \n ID = ?
CREATE TABLE FOO (F_FIELD1 BIGINT NOT NULL,F_FIELD2_FIELD1 BIGINT,F_FIELD2_FIELD2 BIGINT,F_FIELD2_FIELD3 BIGINT,F_FIELD3 BOOLEAN NOT NULL)
create table state_bird (state varchar(32),bird varchar(32))
insert into folder values(4, 'Folder 2_1', 3)
select firstName from ibtest.names where id=${value}
select id, name from product where name = #{value}
SELECT * FROM BLOG WHERE ID in
create table lineitem (orderid int not null,linenum int not null,itemid varchar(10) not null,quantity int not null,unitprice decimal(10,2) not null,constraint pk_lineitem primary key (orderid, linenum))
create table friend ( user_id int, friend_id int)
create table person ( id int, firstName varchar(100), lastName varchar(100))
create table users ( id int, name varchar(20) , dept_id int)
SELECT * FROM blog
select * from users order by uid
create table GrandFather ( id int, name varchar(100))
SELECT * FROM ${tableName:users} ORDER BY ${orderColumn:id}", props)).isEqualTo("SELECT * FROM members ORDER BY member_id
CREATE TABLE blog (id INT,title VARCHAR(255))
insert into permissions values ('resource2', 'user1', 'update')
select * from sptest.names where id >= lowestId;
create table contact ( id int, address varchar(100), phone varchar(32), person_id int, foreign key (person_id) references person(id))
CREATE TABLE subject ( id INT NOT NULL, name VARCHAR(20), age INT NOT NULL, height INT, weight INT, active BIT, dt TIMESTAMP)
CREATE TABLE comment (id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,post_id INT NOT NULL,name LONG VARCHAR NOT NULL,comment LONG VARCHAR NOT NULL,PRIMARY KEY (id))
create table Father ( id int, name varchar(100))
create table users ( id int, name varchar(20))
select firstName from ibtest.names where id=${named}
