select clientprocessid, clientinfo from SYSTEM.CONNECTIONS
select count(*) from execute_ten_million_with_result_sets;
select name from %sbooze
CREATE TABLE huge_select (f1 INTEGER GENERATED BY DEFAULT AS IDENTITY(s1))
SELECT COUNT(*) FROM autocommit_set
select * from executemany_table;
select * from typetest
CREATE TABLE autocommit_set (f1 integer)
create table typetest (id integer GENERATED ALWAYS AS IDENTITY, time_col time, timestamp_col timestamp)
create table perf_test (a int,b char)
select * from perf_test
SELECT * FROM t
select * from typetest order by id desc limit 1
CREATE TABLE t (x NUMERIC(%s,%s))
CREATE TABLE ten (f1 INTEGER)
select number_col from typetest order by id desc limit 1
create table typetest (id integer GENERATED ALWAYS AS IDENTITY, binary_col binary(100000))
SELECT 3 FROM DUAL UNION ALL SELECT 4 FROM DUAL
create table typetest (id integer GENERATED ALWAYS AS IDENTITY, date_col date)
SELECT COUNT(*) FROM commit_table
CREATE TABLE rollback_table (f1 integer)
select 1 from dual;
CREATE TABLE execute_ten_million_with_result_sets (value INTEGER)
CREATE TABLE rollback_disconnect (f1 integer)
select decimal_col from typetest order by id desc limit 1
select 1 from dual
SELECT COUNT(*) FROM rollback_table
SELECT 1 FROM DUAL UNION ALL SELECT 2 FROM DUAL
SELECT COUNT(*) FROM rollback_disconnect
SELECT 1 FROM DUAL WHERE FALSE
INSERT INTO rollback_disconnect VALUES (1)
INSERT INTO ten VALUES (1)
CREATE TABLE commit_table (f1 integer)
INSERT INTO executemany_table VALUES (?, ?)
select * from hockey
create table %sbooze (name varchar(20))
INSERT INTO autocommit_set VALUES (1)
SELECT * FROM executemany_table
CREATE TABLE executemany_table (f1 INTEGER, f2 INTEGER)
INSERT INTO commit_table VALUES (1)
INSERT INTO rollback_table VALUES (1)
SELECT id, name FROM names where age > ? ORDER BY id
create table typetest (id integer GENERATED ALWAYS AS IDENTITY, timestamp_col timestamp)
SELECT 1 FROM DUAL
CREATE TABLE names ( id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY, name VARCHAR(30) DEFAULT '' NOT NULL, age INTEGER DEFAULT 0 )
SELECT * FROM huge_select
