CREATE TABLE %s (foo int)
SELECT COUNT(1) FROM a
CREATE TABLE public.foo (a INTEGER)
CREATE TABLE foo (test VARCHAR)
SELECT * FROM b
INSERT INTO foo VALUES('bar')
SELECT * FROM foo
SELECT count(1) FROM a
INSERT INTO a VALUES(1)
