CREATE TABLE countries( country_name VARCHAR(255) NOT NULL, country_code VARCHAR(5) NOT NULL)
CREATE TABLE blacklisted_ips( ip VARCHAR(64) NOT NULL, date DATE NOT NULL)
SELECT MAX(id) FROM tiles;
CREATE TABLE adgroups( id INTEGER IDENTITY(1,1) NOT NULL, created_at TIMESTAMP DEFAULT SYSDATE NOT NULL, locale VARCHAR(14) NOT NULL, PRIMARY KEY (id))
SELECT MIN(id) FROM channels WHERE name = 'android') WHERE id in (SELECT adgroup_id FROM tiles WHERE id in (529, 630, 631, 632));
CREATE TABLE adgroup_sites( id INTEGER IDENTITY(1,1) NOT NULL, site VARCHAR(1024) NOT NULL, adgroup_id INT NOT NULL, created_at TIMESTAMP DEFAULT SYSDATE NOT NULL, FOREIGN KEY (adgroup_id) REFERENCES adgroups (id), PRIMARY KEY (id))
CREATE TABLE temp_newtab_stats_daily( date DATE NOT NULL, newtabs INT DEFAULT 0 NOT NULL, month INT DEFAULT 0 NOT NULL, week INT DEFAULT 0 NOT NULL, year INT DEFAULT 0 NOT NULL, locale VARCHAR(14) NOT NULL, country_code VARCHAR(5) NOT NULL, os VARCHAR(64) NOT NULL, browser VARCHAR(64) NOT NULL, version VARCHAR(64) NOT NULL, device VARCHAR(64) NOT NULL)
SELECT MAX(id) FROM adgroups;
CREATE TABLE ss_event ( client_id VARCHAR(64) NOT NULL, tab_id VARCHAR(64) NOT NULL, addon_version VARCHAR(64) NOT NULL, source VARCHAR(64) NOT NULL, session_id VARCHAR(64), shield_variant VARCHAR(64), page VARCHAR(64) NOT NULL, experiment_id VARCHAR(64), action_position VARCHAR(16) NOT NULL, event VARCHAR(16) NOT NULL, recommendation_url VARCHAR(255), recommender_type VARCHAR(64), highlight_type VARCHAR(64), share_provider VARCHAR(64), metadata_source VARCHAR(64), receive_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, date DATE NOT NULL, locale VARCHAR(14) NOT NULL, country_code VARCHAR(5) NOT NULL, os VARCHAR(64) NOT NULL, browser VARCHAR(64) NOT NULL, version VARCHAR(64) NOT NULL, device VARCHAR(64) NOT NULL)
SELECT MIN(id) FROM channels WHERE name = 'desktop');
insert into countries VALUES('Anonymous Proxy','A1')
CREATE TABLE assa_events_daily ( client_id VARCHAR(64) NOT NULL, addon_version VARCHAR(64) NOT NULL, source VARCHAR(64) NOT NULL, session_id VARCHAR(64) NOT NULL, page VARCHAR(64) NOT NULL, action_position VARCHAR(16) NOT NULL, event VARCHAR(64) NOT NULL, receive_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, date DATE NOT NULL, locale VARCHAR(14) NOT NULL, country_code VARCHAR(5) NOT NULL, os VARCHAR(64) NOT NULL, browser VARCHAR(64) NOT NULL, version VARCHAR(64) NOT NULL, device VARCHAR(64) NOT NULL)
CREATE TABLE tiles ( id INTEGER IDENTITY(1,1) NOT NULL, target_url TEXT NOT NULL, bg_color VARCHAR(16) NOT NULL, title VARCHAR(255) NOT NULL, type VARCHAR(40) NOT NULL, image_uri TEXT NOT NULL, enhanced_image_uri TEXT, locale VARCHAR(14) NOT NULL, created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))
select * from temp_app_stats;
CREATE TABLE ss_session ( client_id VARCHAR(64) NOT NULL, tab_id VARCHAR(64) NOT NULL, addon_version VARCHAR(64) NOT NULL, load_reason VARCHAR(64) NOT NULL, page VARCHAR(64) NOT NULL, unload_reason VARCHAR(64) NOT NULL, experiment_id VARCHAR(64), max_scroll_depth INTEGER NOT NULL, load_latency INTEGER NOT NULL, total_bookmarks INTEGER NOT NULL, total_history_size INTEGER NOT NULL, session_duration INTEGER NOT NULL, session_id VARCHAR(64), shield_variant VARCHAR(64), receive_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, date DATE NOT NULL, locale VARCHAR(14) NOT NULL, country_code VARCHAR(5) NOT NULL, os VARCHAR(64) NOT NULL, browser VARCHAR(64) NOT NULL, version VARCHAR(64) NOT NULL, device VARCHAR(64) NOT NULL)
CREATE TABLE activity_stream_mobile_events_daily ( client_id VARCHAR(64) NOT NULL, build VARCHAR(64) NOT NULL, app_version VARCHAR(64) NOT NULL, page VARCHAR(64) NOT NULL, action_position VARCHAR(16), source VARCHAR(64), release_channel VARCHAR(32), event VARCHAR(64) NOT NULL, receive_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, date DATE NOT NULL, locale VARCHAR(14) NOT NULL, country_code VARCHAR(5) NOT NULL, os VARCHAR(64) NOT NULL, browser VARCHAR(64) NOT NULL, version VARCHAR(64) NOT NULL, device VARCHAR(14) NOT NULL)
CREATE TABLE activity_stream_performance_daily ( client_id VARCHAR(64) NOT NULL, tab_id VARCHAR(64) NOT NULL, addon_version VARCHAR(64) NOT NULL, source VARCHAR(64) NOT NULL, session_id VARCHAR(64), experiment_id VARCHAR(64), event VARCHAR(64) NOT NULL, event_id VARCHAR(64) NOT NULL, value INTEGER NOT NULL, receive_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, date DATE NOT NULL, locale VARCHAR(14) NOT NULL, country_code VARCHAR(5) NOT NULL, os VARCHAR(64) NOT NULL, browser VARCHAR(64) NOT NULL, version VARCHAR(64) NOT NULL, device VARCHAR(64) NOT NULL)
CREATE TABLE ss_masga ( client_id VARCHAR(64) NOT NULL, tab_id VARCHAR(64) NOT NULL, addon_version VARCHAR(64) NOT NULL, source VARCHAR(64) NOT NULL, session_id VARCHAR(64), experiment_id VARCHAR(64), event VARCHAR(64) NOT NULL, event_id VARCHAR(64) NOT NULL, value INTEGER NOT NULL, receive_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, date DATE NOT NULL, locale VARCHAR(14) NOT NULL, country_code VARCHAR(5) NOT NULL, os VARCHAR(64) NOT NULL, browser VARCHAR(64) NOT NULL, version VARCHAR(64) NOT NULL, device VARCHAR(64) NOT NULL)
UPDATE activity_stream_stats_daily SET addon_version_temp = addon_version WHERE page_temp = TIMELINE_BOOKMAR
CREATE TABLE assa_performance_daily ( client_id VARCHAR(64) NOT NULL, addon_version VARCHAR(64) NOT NULL, source VARCHAR(64) NOT NULL, session_id VARCHAR(64), page VARCHAR(64) NOT NULL, event VARCHAR(64) NOT NULL, event_id VARCHAR(64) NOT NULL, value INTEGER NOT NULL, receive_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, date DATE NOT NULL, locale VARCHAR(14) NOT NULL, country_code VARCHAR(5) NOT NULL, os VARCHAR(64) NOT NULL, browser VARCHAR(64) NOT NULL, version VARCHAR(64) NOT NULL, device VARCHAR(64) NOT NULL)
select * from temp_imp_stats;
CREATE TABLE assa_router_events_daily ( impression_id VARCHAR(64) NOT NULL ENCODE ZSTD, addon_version VARCHAR(64) NOT NULL ENCODE ZSTD, source VARCHAR(64) NOT NULL ENCODE ZSTD, event VARCHAR(64) NOT NULL ENCODE ZSTD, value VARCHAR(256) ENCODE ZSTD, message_id VARCHAR(128) NOT NULL ENCODE ZSTD, receive_at TIMESTAMP WITHOUT TIME ZONE NOT NULL ENCODE ZSTD, release_channel VARCHAR(16) ENCODE ZSTD, shield_id VARCHAR(256) ENCODE ZSTD, date DATE NOT NULL ENCODE ZSTD, locale VARCHAR(14) NOT NULL ENCODE BYTEDICT, country_code VARCHAR(5) NOT NULL ENCODE BYTEDICT, os VARCHAR(64) NOT NULL ENCODE ZSTD, browser VARCHAR(64) NOT NULL ENCODE ZSTD, version VARCHAR(64) NOT NULL ENCODE ZSTD, device VARCHAR(64) NOT NULL ENCODE ZSTD)
CREATE TABLE unique_hlls ( unique_counts_daily_id INTEGER, index SMALLINT DEFAULT '0' NOT NULL, value SMALLINT DEFAULT '0' NOT NULL, FOREIGN KEY(unique_counts_daily_id) REFERENCES unique_counts_daily (id))
CREATE TABLE watchdog_proxy_events_daily ( receive_at TIMESTAMP WITHOUT TIME ZONE NOT NULL ENCODE ZSTD, date DATE NOT NULL ENCODE ZSTD, event VARCHAR(64) NOT NULL ENCODE ZSTD, consumer_name VARCHAR(128) ENCODE ZSTD, watchdog_id VARCHAR(128) ENCODE ZSTD, type VARCHAR(64) ENCODE ZSTD, poller_id VARCHAR(128) ENCODE ZSTD, items_in_queue INTEGER ENCODE ZSTD, items_in_progress INTEGER ENCODE ZSTD, items_in_waiting INTEGER ENCODE ZSTD, photodna_tracking_id VARCHAR(128) ENCODE ZSTD, worker_id VARCHAR(128) ENCODE ZSTD, is_match BOOLEAN ENCODE ZSTD, is_error BOOLEAN ENCODE ZSTD, timing_sent INTEGER ENCODE ZSTD, timing_received INTEGER ENCODE ZSTD, timing_submitted INTEGER ENCODE ZSTD, sample_id SMALLINT NOT NULL DEFAULT (random() * 100) ENCODE ZSTD)
SELECT locale FROM tiles ORDER BY id;
CREATE TABLE activity_stream_impression_daily ( client_id VARCHAR(64) NOT NULL, tile_id INTEGER NOT NULL, addon_version VARCHAR(64) NOT NULL, date DATE NOT NULL, impressions INTEGER DEFAULT '0' NOT NULL, clicks INTEGER DEFAULT '0' NOT NULL, pinned INTEGER DEFAULT '0' NOT NULL, blocked INTEGER DEFAULT '0' NOT NULL, pocketed INTEGER DEFAULT '0' NOT NULL, position INTEGER DEFAULT '0' NOT NULL, source VARCHAR(64) NOT NULL, locale VARCHAR(14) NOT NULL, country_code VARCHAR(5) NOT NULL, os VARCHAR(64) NOT NULL, browser VARCHAR(64) NOT NULL, version VARCHAR(64) NOT NULL, device VARCHAR(64) NOT NULL, blacklisted BOOLEAN DEFAULT 'false' NOT NULL, user_prefs INTEGER, experiment_id VARCHAR(64))
CREATE TABLE assa_masga_daily ( client_id VARCHAR(64) NOT NULL, addon_version VARCHAR(64) NOT NULL, source VARCHAR(64) NOT NULL, session_id VARCHAR(64), page VARCHAR(64) NOT NULL, event VARCHAR(64) NOT NULL, value INTEGER NOT NULL, receive_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, date DATE NOT NULL, locale VARCHAR(14) NOT NULL, country_code VARCHAR(5) NOT NULL, os VARCHAR(64) NOT NULL, browser VARCHAR(64) NOT NULL, version VARCHAR(64) NOT NULL, device VARCHAR(64) NOT NULL)
CREATE TABLE ss_impression ( client_id VARCHAR(64) NOT NULL, addon_version VARCHAR(64) NOT NULL, tile_id INTEGER NOT NULL, date DATE NOT NULL, impressions INTEGER DEFAULT '0' NOT NULL, clicks INTEGER DEFAULT '0' NOT NULL, pinned INTEGER DEFAULT '0' NOT NULL, blocked INTEGER DEFAULT '0' NOT NULL, pocketed INTEGER DEFAULT '0' NOT NULL, position INTEGER DEFAULT '0' NOT NULL, source VARCHAR(64) NOT NULL, locale VARCHAR(14) NOT NULL, country_code VARCHAR(5) NOT NULL, os VARCHAR(64) NOT NULL, browser VARCHAR(64) NOT NULL, version VARCHAR(64) NOT NULL, device VARCHAR(64) NOT NULL, blacklisted BOOLEAN DEFAULT 'false' NOT NULL, user_prefs INTEGER, tp_version VARCHAR(64), experiment_id VARCHAR(64))
CREATE TABLE channels ( id INTEGER IDENTITY(1,1) NOT NULL, name VARCHAR(16) NOT NULL, created_at TIMESTAMP WITHOUT TIME ZONE, PRIMARY KEY (id))
CREATE TABLE assa_impression_stats_daily ( client_id VARCHAR(64) NOT NULL, tile_id INTEGER NOT NULL, addon_version VARCHAR(64) NOT NULL, date DATE NOT NULL, impressions INTEGER DEFAULT '0' NOT NULL, clicks INTEGER DEFAULT '0' NOT NULL, pinned INTEGER DEFAULT '0' NOT NULL, blocked INTEGER DEFAULT '0' NOT NULL, pocketed INTEGER DEFAULT '0' NOT NULL, position INTEGER DEFAULT '0' NOT NULL, page VARCHAR(64) NOT NULL, source VARCHAR(64) NOT NULL, locale VARCHAR(14) NOT NULL, country_code VARCHAR(5) NOT NULL, os VARCHAR(64) NOT NULL, browser VARCHAR(64) NOT NULL, version VARCHAR(64) NOT NULL, device VARCHAR(64) NOT NULL, blacklisted BOOLEAN DEFAULT 'false' NOT NULL, user_prefs INTEGER)
SELECT count(*) FROM accounts
update tiles set image_uri = %s  where id in (%s)
select count(*) from %s
CREATE TABLE site_stats_daily( date DATE NOT NULL, month INT DEFAULT 0 NOT NULL, week INT DEFAULT 0 NOT NULL, year INT DEFAULT 0 NOT NULL, locale VARCHAR(14) NOT NULL, url VARCHAR(255) NOT NULL, country_code VARCHAR(5) NOT NULL, os VARCHAR(64) NOT NULL, browser VARCHAR(64) NOT NULL, version VARCHAR(64) NOT NULL, device VARCHAR(64) NOT NULL, impressions INTEGER DEFAULT '0' NOT NULL, clicks INTEGER DEFAULT '0' NOT NULL, pinned INTEGER DEFAULT '0' NOT NULL, blocked INTEGER DEFAULT '0' NOT NULL, sponsored_link INTEGER DEFAULT '0' NOT NULL, sponsored INTEGER DEFAULT '0' NOT NULL)
SELECT count(*) FROM campaigns
CREATE TABLE firefox_onboarding_events_daily ( client_id VARCHAR(64) NOT NULL, addon_version VARCHAR(64) NOT NULL, session_id VARCHAR(64) NOT NULL, page VARCHAR(64) NOT NULL, event VARCHAR(64) NOT NULL, tour_id VARCHAR(64), impression INTEGER NOT NULL, category VARCHAR(64) NOT NULL, receive_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, date DATE NOT NULL, locale VARCHAR(14) NOT NULL, country_code VARCHAR(5) NOT NULL, os VARCHAR(64) NOT NULL, browser VARCHAR(64) NOT NULL, version VARCHAR(64) NOT NULL, device VARCHAR(14) NOT NULL)
update tiles set enhanced_image_uri = %s  where id in (%s)
CREATE TABLE firefox_onboarding_sessions_daily ( client_id VARCHAR(64) NOT NULL, addon_version VARCHAR(64) NOT NULL, session_begin BIGINT NOT NULL, session_end BIGINT NOT NULL, session_id VARCHAR(64) NOT NULL, impression INTEGER NOT NULL, page VARCHAR(64) NOT NULL, event VARCHAR(64) NOT NULL, category VARCHAR(64) NOT NULL, tour_source VARCHAR(64) NOT NULL, receive_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, date DATE NOT NULL, locale VARCHAR(14) NOT NULL, country_code VARCHAR(5) NOT NULL, os VARCHAR(64) NOT NULL, browser VARCHAR(64) NOT NULL, version VARCHAR(64) NOT NULL, device VARCHAR(14) NOT NULL)
CREATE TABLE ss_performance ( client_id VARCHAR(64) NOT NULL, tab_id VARCHAR(64) NOT NULL, addon_version VARCHAR(64) NOT NULL, source VARCHAR(64) NOT NULL, session_id VARCHAR(64), shield_variant VARCHAR(64), experiment_id VARCHAR(64), event VARCHAR(64) NOT NULL, event_id VARCHAR(64) NOT NULL, metadata_source VARCHAR(64), value INTEGER NOT NULL, receive_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, date DATE NOT NULL, locale VARCHAR(14) NOT NULL, country_code VARCHAR(5) NOT NULL, os VARCHAR(64) NOT NULL, browser VARCHAR(64) NOT NULL, version VARCHAR(64) NOT NULL, device VARCHAR(64) NOT NULL)
CREATE TABLE application_stats_daily( date DATE NOT NULL, month INT DEFAULT 0 NOT NULL, week INT DEFAULT 0 NOT NULL, year INT DEFAULT 0 NOT NULL, locale VARCHAR(14) NOT NULL, action VARCHAR(255) NOT NULL, country_code VARCHAR(5) NOT NULL, os VARCHAR(64) NOT NULL, browser VARCHAR(64) NOT NULL, version VARCHAR(64) NOT NULL, device VARCHAR(64) NOT NULL, ver VARCHAR(16) NOT NULL, count INT DEFAULT 0 NOT NULL)
CREATE TABLE activity_stream_mobile_stats_daily ( client_id VARCHAR(64) NOT NULL, build VARCHAR(64) NOT NULL, app_version VARCHAR(64) NOT NULL, session_duration INTEGER NOT NULL, release_channel VARCHAR(32), receive_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, date DATE NOT NULL, locale VARCHAR(14) NOT NULL, country_code VARCHAR(5) NOT NULL, os VARCHAR(64) NOT NULL, browser VARCHAR(64) NOT NULL, version VARCHAR(64) NOT NULL, device VARCHAR(14) NOT NULL)
CREATE TABLE ping_centre_main ( client_id VARCHAR(64) NOT NULL, shield_id VARCHAR(256) NOT NULL, release_channel VARCHAR(32) NOT NULL, event VARCHAR(64) NOT NULL, value VARCHAR(256) NOT NULL, receive_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, date DATE NOT NULL, locale VARCHAR(14) NOT NULL, country_code VARCHAR(5) NOT NULL, os VARCHAR(64) NOT NULL, browser VARCHAR(64) NOT NULL, version VARCHAR(64) NOT NULL, device VARCHAR(14) NOT NULL)
CREATE TABLE impression_stats_daily ( tile_id INTEGER, date DATE NOT NULL, impressions INTEGER DEFAULT '0' NOT NULL, clicks INTEGER DEFAULT '0' NOT NULL, pinned INTEGER DEFAULT '0' NOT NULL, blocked INTEGER DEFAULT '0' NOT NULL, sponsored_link INTEGER DEFAULT '0' NOT NULL, sponsored INTEGER DEFAULT '0' NOT NULL, position INTEGER DEFAULT '0' NOT NULL, enhanced BOOLEAN DEFAULT FALSE NOT NULL, locale VARCHAR(14) NOT NULL, country_code VARCHAR(5) NOT NULL, os VARCHAR(64) NOT NULL, browser VARCHAR(64) NOT NULL, version VARCHAR(64) NOT NULL, device VARCHAR(64) NOT NULL, FOREIGN KEY(tile_id) REFERENCES tiles (id))
CREATE TABLE activity_stream_masga ( client_id VARCHAR(64) NOT NULL, tab_id VARCHAR(64) NOT NULL, addon_version VARCHAR(64) NOT NULL, source VARCHAR(64) NOT NULL, session_id VARCHAR(64), experiment_id VARCHAR(64), event VARCHAR(64) NOT NULL, event_id VARCHAR(64) NOT NULL, value INTEGER NOT NULL, receive_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, date DATE NOT NULL, locale VARCHAR(14) NOT NULL, country_code VARCHAR(5) NOT NULL, os VARCHAR(64) NOT NULL, browser VARCHAR(64) NOT NULL, version VARCHAR(64) NOT NULL, device VARCHAR(64) NOT NULL)
update adgroups set type = suggested  where id in (select distinct adgroup_id from adgroup_sites)
CREATE TABLE unique_counts_daily ( id INTEGER IDENTITY(1,1) NOT NULL, tile_id INTEGER, date DATE NOT NULL, impression BOOLEAN NOT NULL, locale VARCHAR(14) NOT NULL, country_code VARCHAR(5) NOT NULL, PRIMARY KEY (id), FOREIGN KEY(tile_id) REFERENCES tiles (id))
CREATE TABLE firefox_onboarding_sessions2_daily ( client_id VARCHAR(64) NOT NULL, addon_version VARCHAR(64) NOT NULL, category VARCHAR(64) NOT NULL, page VARCHAR(64) NOT NULL, parent_session_id VARCHAR(64) NOT NULL, root_session_id VARCHAR(64) NOT NULL, session_begin BIGINT NOT NULL, session_end BIGINT NOT NULL, session_id VARCHAR(64) NOT NULL, tour_type VARCHAR(64) NOT NULL, type VARCHAR(64) NOT NULL, release_channel VARCHAR(16) NOT NULL, receive_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, date DATE NOT NULL, locale VARCHAR(14) NOT NULL, country_code VARCHAR(5) NOT NULL, os VARCHAR(64) NOT NULL, browser VARCHAR(64) NOT NULL, version VARCHAR(64) NOT NULL, device VARCHAR(14) NOT NULL)
CREATE TABLE temp_impression_stats_daily ( tile_id INTEGER, date DATE NOT NULL, impressions INTEGER DEFAULT '0' NOT NULL, clicks INTEGER DEFAULT '0' NOT NULL, pinned INTEGER DEFAULT '0' NOT NULL, blocked INTEGER DEFAULT '0' NOT NULL, sponsored_link INTEGER DEFAULT '0' NOT NULL, sponsored INTEGER DEFAULT '0' NOT NULL, position INTEGER DEFAULT '0' NOT NULL, enhanced BOOLEAN DEFAULT FALSE NOT NULL, locale VARCHAR(14) NOT NULL, country_code VARCHAR(5) NOT NULL, os VARCHAR(64) NOT NULL, browser VARCHAR(64) NOT NULL, version VARCHAR(64) NOT NULL, device VARCHAR(64) NOT NULL, FOREIGN KEY(tile_id) REFERENCES tiles (id), month INTEGER DEFAULT '0' NOT NULL, week INTEGER DEFAULT '0' NOT NULL, year INTEGER DEFAULT '0' NOT NULL)
CREATE TABLE activity_stream_events_daily ( client_id VARCHAR(64) NOT NULL, tab_id VARCHAR(64) NOT NULL, addon_version VARCHAR(16) NOT NULL, source VARCHAR(64) NOT NULL, page VARCHAR(16) NOT NULL, action_position VARCHAR(16) NOT NULL, event VARCHAR(16) NOT NULL, receive_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, date DATE NOT NULL, locale VARCHAR(14) NOT NULL, country_code VARCHAR(5) NOT NULL, os VARCHAR(64) NOT NULL, browser VARCHAR(64) NOT NULL, version VARCHAR(64) NOT NULL, device VARCHAR(64) NOT NULL)
UPDATE activity_stream_events_daily SET addon_version_temp = addon_version WHERE page_temp = TIMELINE_BOOKMAR
CREATE TABLE distributions ( id INTEGER IDENTITY(1,1) NOT NULL, url TEXT NOT NULL, created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))
CREATE TABLE ping_centre_test_pilot ( client_id VARCHAR(64) NOT NULL, event_type VARCHAR(64) NOT NULL, object VARCHAR(64), client_time INTEGER NOT NULL, variants VARCHAR(64), addon_id VARCHAR(64) NOT NULL, addon_version VARCHAR(64) NOT NULL, firefox_version VARCHAR(64) NOT NULL, receive_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, date DATE NOT NULL, os_name VARCHAR(64) NOT NULL, os_version VARCHAR(64) NOT NULL, locale VARCHAR(14) NOT NULL, raw_ping VARCHAR(16384) NOT NULL)
CREATE TABLE firefox_onboarding_events2_daily ( client_id VARCHAR(64) NOT NULL, addon_version VARCHAR(64) NOT NULL, bubble_state VARCHAR(16) NOT NULL, category VARCHAR(64) NOT NULL, current_tour_id VARCHAR(64) NOT NULL, logo_state VARCHAR(16) NOT NULL, notification_impression INTEGER NOT NULL, notification_state VARCHAR(16) NOT NULL, page VARCHAR(64) NOT NULL, parent_session_id VARCHAR(64) NOT NULL, root_session_id VARCHAR(64) NOT NULL, target_tour_id VARCHAR(64) NOT NULL, timestamp BIGINT NOT NULL, tour_type VARCHAR(16) NOT NULL, type VARCHAR(64) NOT NULL, width INTEGER NOT NULL, release_channel VARCHAR(16) NOT NULL, receive_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, date DATE NOT NULL, locale VARCHAR(14) NOT NULL, country_code VARCHAR(5) NOT NULL, os VARCHAR(64) NOT NULL, browser VARCHAR(64) NOT NULL, version VARCHAR(64) NOT NULL, device VARCHAR(14) NOT NULL)
CREATE TABLE assa_sessions_daily ( client_id VARCHAR(64) NOT NULL, addon_version VARCHAR(64) NOT NULL, page VARCHAR(64) NOT NULL, session_duration INTEGER NOT NULL, session_id VARCHAR(64) NOT NULL, load_trigger_type VARCHAR(64), load_trigger_ts DOUBLE PRECISION, visibility_event_rcvd_ts DOUBLE PRECISION, receive_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, date DATE NOT NULL, locale VARCHAR(14) NOT NULL, country_code VARCHAR(5) NOT NULL, os VARCHAR(64) NOT NULL, browser VARCHAR(64) NOT NULL, version VARCHAR(64) NOT NULL, device VARCHAR(64) NOT NULL)
CREATE TABLE newtab_stats_daily( date DATE NOT NULL, newtabs INT DEFAULT 0 NOT NULL, month INT DEFAULT 0 NOT NULL, week INT DEFAULT 0 NOT NULL, year INT DEFAULT 0 NOT NULL, locale VARCHAR(14) NOT NULL, country_code VARCHAR(5) NOT NULL, os VARCHAR(64) NOT NULL, browser VARCHAR(64) NOT NULL, version VARCHAR(64) NOT NULL, device VARCHAR(64) NOT NULL)
CREATE TABLE activity_stream_stats_daily ( client_id VARCHAR(64) NOT NULL, tab_id VARCHAR(64) NOT NULL, addon_version VARCHAR(16) NOT NULL, load_reason VARCHAR(64) NOT NULL, source VARCHAR(64) NOT NULL, unload_reason VARCHAR(64) NOT NULL, max_scroll_depth INTEGER NOT NULL, load_latency INTEGER NOT NULL, click_position INTEGER NOT NULL, total_bookmarks INTEGER NOT NULL, total_history_size INTEGER NOT NULL, session_duration INTEGER NOT NULL, receive_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, locale VARCHAR(14) NOT NULL, country_code VARCHAR(5) NOT NULL, os VARCHAR(64) NOT NULL, browser VARCHAR(64) NOT NULL, version VARCHAR(64) NOT NULL, device VARCHAR(64) NOT NULL)
SELECT id FROM channels WHERE name = 'desktop');
