SELECT * FROM DGB_ACCESS_LOG_LOCATIONS
CREATE INDEX DGB_DOCUMENTS_DOC_CONTENT_IDX ON DGB_DOCUMENTS (DOC_CONTENT);
SELECT COUNT(*) FROM ${tableName}');
SELECT * FROM table_name
SELECT * FROM " + DGB_STORAGE + " WHERE 
SELECT COUNT(*) FROM DGB_ACCESS_LOG_LOCATIONS
SELECT * FROM PUBLIC.SCHEMAS WHERE HAS_PRIVILEGES='TRUE'
SELECT * FROM DGB_ACCESS_LOG
SELECT COUNT(*) FROM ";
SELECT * FROM DGB_MEMORY_LOG
Create Table				stmt.executeUpdate(createTableQuery)
SELECT COUNT(*) FROM DGB_ACCESS_LOG
SELECT * FROM ";
SELECT COUNT(*) FROM DGB_MEMORY_LOG
SELECT * FROM ${tableName} WHERE 
select row from the table.');
