create table '%-.200s' (errno: %d)
create table geometry_table (location geometry)
create table bikini_bottom (name varchar(255) primary key)
create table mbcj_test_isolated.bikini_bottom (name varchar(255) primary key)
insert into bikini_bottom values('SpongeBob')
insert into bikini_bottom values('Patrick')
create table json_b (h varchar(255), j JSON, k varchar(255))
INSERT INTO json_b VALUES ('sponge', '{}', 'bob')
create table fsp_check (column_ datetime(0))
insert into bikini_bottom values('Squidward')
insert into geometry_table values(ST_GeomFromText('POINT(40.717957 -73.736501)'))
insert into bikini_bottom values('Rocky')
update bikini_bottom set name = Patrick  where name = SpongeBob
create table json_support_validation (i INT, j JSON)
