SELECT COUNT(*) FROM BOOKS
SELECT * FROM BOOKS WHERE TITLE = ?
SELECT TITLE FROM BOOKS
SELECT * FROM BOOKS
CREATE TABLE BOOKS (TITLE VARCHAR(42) NULL, AUTHOR VARCHAR(42) NULL, PRICE DECIMAL(10,2) NOT NULL)
SELECT * FROM Buecher WHERE TITEL = ?
SELECT ID FROM Buecher ORDER BY ID ASC
CREATE TABLE TEST0 (spotfix_id BIGINT NULL)
CREATE TABLE Buecher (TITEL VARCHAR(42) NULL, AUTOR VARCHAR(42) NULL, PREIS DECIMAL(10,2) NOT NULL)
CREATE TABLE Buecher (ID INT NULL, AUTOR VARCHAR(42) NULL, PREIS DECIMAL(10,2) NOT NULL)
SELECT * FROM TEST0
CREATE TABLE `BOOKS` (`ID` int(10) unsigned NOT NULL AUTO_INCREMENT, `TITLE` varchar(42) DEFAULT NULL, `AUTHOR` varchar(42) DEFAULT NULL,`PRICE` double DEFAULT NULL, PRIMARY KEY (`ID`))
CREATE TABLE Books (TITLE VARCHAR(42) NULL, AUT_HOR VARCHAR(42) NULL, PRICE DECIMAL(10,2) NOT NULL)
create table BooksDAO.createBooksTable()
