SELECT STRATEGY_ID FROM MYTABLE WHERE FEATURE_NAME = 'F2'
INSERT INTO TOGGLZ VALUES ('F1', 1, 'ck, admin')
CREATE TABLE %TABLE% (FEATURE_NAME VARCHAR(100) PRIMARY KEY, FEATURE_ENABLED INTEGER, FEATURE_USERS VARCHAR(2000))
INSERT INTO TOGGLZ VALUES ('F1', 1, 'myStrategy', 'param23=foobar')
SELECT FEATURE_NAME, FEATURE_USERS FROM TOGGLZ ORDER BY FEATURE_NAME
SELECT FEATURE_NAME, FEATURE_USERS, STRATEGY_ID, STRATEGY_PARAMS FROM %TABLE%
SELECT FEATURE_NAME, STRATEGY_ID, STRATEGY_PARAMS FROM TOGGLZ ORDER BY FEATURE_NAME
INSERT INTO TOGGLZ VALUES ('F2', 1, '')
INSERT INTO TOGGLZ VALUES ('F3', 1, NULL)
SELECT FEATURE_USERS FROM TOGGLZ
SELECT * FROM %TABLE%
SELECT STRATEGY_ID FROM TOGGLZ WHERE FEATURE_NAME = 'F1'
SELECT FEATURE_ENABLED, STRATEGY_ID, STRATEGY_PARAMS FROM %TABLE% WHERE FEATURE_NAME = ?
SELECT STRATEGY_PARAMS FROM MYTABLE WHERE FEATURE_NAME = 'F2'
SELECT COUNT(*) FROM MYTABLE WHERE FEATURE_NAME = 'F2'
SELECT FEATURE_NAME FROM TOGGLZ
SELECT FEATURE_NAME,STRATEGY_ID,STRATEGY_PARAMS FROM TOGGLZ
SELECT FEATURE_ENABLED FROM TOGGLZ WHERE FEATURE_NAME = 'F1'
INSERT INTO TOGGLZ VALUES ('F1', 0, NULL, NULL)
SELECT STRATEGY_PARAMS FROM TOGGLZ WHERE FEATURE_NAME = 'F1'
SELECT FEATURE_ENABLED FROM MYTABLE WHERE FEATURE_NAME = 'F2'
SELECT COUNT(*) FROM TOGGLZ WHERE FEATURE_NAME = 'F1'
