SELECT * FROM SPLIT_INFO WHERE POC=\
CREATE TABLE YUVCONFIG (FileName varchar(600), Width int, Height int, Is10Bit bit, PRIMARY KEY (FileName))
CREATE TABLE SPLIT_INFO (POC INTEGER PRIMARY KEY, size int, data blob)
SELECT * FROM YUVCONFIG WHERE FileName=\
SELECT * FROM TILES_INFO WHERE prePOC=\
